# Generated by Django 6.0.7 on 2026-08-01 02:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loginhistory_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='codemantra', max_length=100)),
                ('public_email', models.EmailField(default='codemantracore@gmail.com', max_length=254)),
                ('public_phone', models.CharField(default='7433937560', max_length=40)),
                ('admin_notification_email', models.EmailField(blank=True, help_text='Where visitor/user activity alerts are sent. Set by the admin.', max_length=254, null=True)),
                ('notify_on_visitor', models.BooleanField(default=True)),
                ('notify_on_signup', models.BooleanField(default=True)),
                ('notify_on_login', models.BooleanField(default=True)),
                ('notify_on_resume_request', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site setting',
            },
        ),
        migrations.CreateModel(
            name='ResumeDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=255, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_requests', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_requests', to='api.resume')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resume_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('display_name', models.CharField(default='Anonymous Visitor', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(default='VISITOR', max_length=20)),
                ('path', models.CharField(blank=True, max_length=300, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
                ('language', models.CharField(blank=True, max_length=40, null=True)),
                ('timezone_name', models.CharField(blank=True, max_length=80, null=True)),
                ('screen', models.CharField(blank=True, max_length=40, null=True)),
                ('device', models.CharField(blank=True, max_length=40, null=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='VisitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=300, null=True)),
                ('event_type', models.CharField(default='PAGE_VIEW', max_length=40)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.visitorlog')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
