# Generated by Django 6.1.1 on 2026-09-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sitesetting_resumedownloadrequest_visitorlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='preview_video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
